"Usage:
    TRADESEQ.R (--group_of_clusters <gc>) (--group_name <gn>) (--starting_cluster <sc>) (--species_name1 <sn1>) (--species_name2 <sn2>) <input1>
    TRADESEQ.R -h | --help
Options:
    -h --help   show this screen.
    <input1>    RDS file containing the integrated and clustered dataset (generated by Asc-Seurat)
    --group_of_clusters  TEST    
    --group_name    test
    --starting_cluster  TEST
" -> doc

suppressMessages(require(docopt))
suppressMessages(require(Seurat))
suppressMessages(require(tidyverse))
suppressMessages(require(dyno))
suppressMessages(require(grDevices))
suppressMessages(require(slingshot))
suppressMessages(require(RColorBrewer))
suppressMessages(require(ComplexHeatmap))
suppressMessages(require(grDevices))
suppressMessages(require(SingleCellExperiment))
suppressMessages(require(dynplot))
suppressMessages(require(dynwrap))
suppressMessages(require(dynfeature))
suppressMessages(require(ggthemes))
suppressMessages(require(tradeSeq))
set.seed(1407)

opts <- docopt(doc)
save.image("test.rda")
#load("test.rda")

BPPARAM <- BiocParallel::bpparam()
BPPARAM$workers <- 2 # use N cores

# Loads the dataset
sc_data <- readRDS(opts$`<input1>`)

groups <- strsplit(opts$gc, split = ",")
names(groups) <- opts$gn
STARTING_CLUSTER = opts$`<sc>`

for (g in 1:length(groups) ) {
    
    to_filter <- base::subset( sc_data,
                               idents = groups[[g]] )
    
    to_filter_ch <- to_filter@meta.data
    to_filter_ch <- base::rownames(to_filter_ch)
    
    sc_data_traj_inf <- base::subset(sc_data,
                                     cells = to_filter_ch)
    
    DefaultAssay(sc_data_traj_inf) <- "RNA"
    
    ### Filtering by the species
    to_filter_spec1 <- sc_data_traj_inf@meta.data %>%
        dplyr::filter( treat == opts$sn1 ) %>%
        rownames()
    
    to_filter_spec2 <- sc_data_traj_inf@meta.data %>%
        dplyr::filter(treat == opts$sn2) %>%
        rownames()
    
    sc_data_traj_spec1 <- base::subset(sc_data_traj_inf,
                                       cells = to_filter_spec1)
    sc_data_traj_spec2 <- base::subset(sc_data_traj_inf,
                                       cells = to_filter_spec2)
    
    species_data <- list(spec1 = sc_data_traj_spec1,
                         spec2 = sc_data_traj_spec2)
    
    names(species_data) <- c(opts$sn1, opts$sn2)
    
    #rm(sc_data_traj_spec1, sc_data_traj_spec2)
    
    for (t in 1:length(species_data) ) {

        sing_cell_data <- species_data[[t]]
        
        COUNTS <- as.matrix(sing_cell_data@assays$RNA@counts)
        COUNTS <- COUNTS[rowSums(COUNTS) > 0, ]
        
        sce <- SingleCellExperiment(assays = List(counts = COUNTS ) )
        reducedDims(sce) <- SimpleList(PCA = sing_cell_data@reductions$pca@cell.embeddings)
        colData(sce)$seurat_clusters <- sing_cell_data$seurat_clusters
        
        sds <- slingshot::slingshot(
            sce,
            clusterLabels = "seurat_clusters",
            start.clus = 0,
            reducedDim = 'PCA',
            shrink = 1L,
            reweight = TRUE,
            reassign = TRUE,
            maxit = 10L,
            smoother = "smooth.spline",
        )
        
        sds2 <- SlingshotDataSet(sds)
        counts <- as.matrix(assays(sds)$counts)
        
        sce_fitted <- fitGAM(counts = counts,
                             sds = sds2,
                             nknots = 6,
                             verbose = T,
                             parallel = TRUE,
                             BPPARAM = BPPARAM)

        saveRDS(sce_fitted,
                file = paste0("TRADEseq_",
                              names(groups)[g],
                              "_",
                              names(species_data)[t],
                              ".rds")
        )
        
        # # test for dynamic expression
        feat_importances <- associationTest(sce_fitted)
        
        
        feat_importances$fdr <- stats::p.adjust(feat_importances$pvalue,
                                      method = "fdr",
                                      n = length(feat_importances$pvalue))
        
        feat_importances$genes <- rownames(feat_importances)
        feat_importances2 <- feat_importances[ ,c(ncol(feat_importances), 1:( ncol(feat_importances) - 1)) ]
        
        write.table( feat_importances2,
                     paste0("TRADEseq_",
                            names(groups)[g],
                            "_",
                            names(species_data)[t],
                            ".csv") ,
                     col.names = T,
                     row.names = F,
                     sep = ",",
                     quote = F,
        )
        
    }
}

